# Site information
site_name:        SEMC Research Computing Documentation
site_description: Documentation for SEMC resources for member institution and NCCAT users.
site_author:      John Pellman
site_url:         https://semc.nysbc.org

# Repository
repo_name: SEMC RC Documentation
repo_url:  https://github.com/nysbc
edit_uri:  https://github.com/nysbc/semcrc-docs

# Copyright
copyright: >-
  Copyright &copy; 2026 &mdash;
  SEMC  Research Computing

# Theme options
theme:
  name: material
  palette:
    primary: black
    scheme: slate
  logo: assets/images/logo.png
  favicon: assets/images/fav.png

nav:
  - Home: index.md
  - Globus: globus.md
